### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by J6ey** [TheMaverickProgrammer/OpenNetBattle#15]
Hello, big Megaman fan here since childhood, I'm really interested in playing around with this project.

I do Android development (mostly Java and Kotlin) and noticed the codebase has mostly C++ and an Android-like structure, but still wasn't sure how to run this.

Can I use Android Studio or do I need Visual Studio to run this? Any tip would be helpful. Thank you :)

**Comment by TheMaverickProgrammer** [comment]
I have some build steps and a youtube video that can help

https://github.com/TheMaverickProgrammer/OpenNetBattle/wiki/Begin-Here

It is for the #development branch so expect not everything to be ready but
you have the latest and greatest code. v2 is expected to be complete in a
month so if you want the new stuff sooner, that's where you want to be. In
order to play, you need an account (last thing to do is to disable this
requirement completely).

Go to battlenetwork.io and create one and some folders to play with. The
youtube video says to edit your config.ini with the url "battlenetwork.io"
and add your account credentials to play.

If you want to play something relatively stable, play the tagged "version
1.0"
https://github.com/TheMaverickProgrammer/OpenNetBattle/tree/v1.0

v1.0 also has an Android directory you can build for mobile. #development
has not been upgraded for mobile in a year (lots of improvements and
refactoring made since then!) but will after PC build is finished.

**Comment by TheMaverickProgrammer** [comment]
Did this help?
